### ISSUE TITLE
Clean up resources after work is done

### ISSUE THREAD

**Issue by alialaraby** [fitnr/sqlite-json#14]
Hello, 
I'm trying to delete a sample.sqlite file after i finished working on it, but there's an error

(There was an error: EBUSY: resource busy or locked)

So I was wondering if there's a way to close the file?

**Comment by fitnr** [comment]
Yes, there is. Should be possible to implement.

**Comment by fitnr** [comment]
I've pushed a fix to the `fix-14` branch. However, I was unable to reproduce your bug? It is possible for you to clone that branch and test your workflow again?

**Comment by alialaraby** [comment]
here's a code snippet of what i'm trying to do.

i get a .zip file within i have .sqilte files, i extract each .sqlite file, convert it to json to get some data, at the end i delete the file with the unlink method, but here's where the issue happen.

i'm using this locally on windows.

` // 3- extract the entry (should be a .sqlite file)
                    let entryPath = `${Constants.SQLITE_DUMPS_FILE_PATH}/${entry['name']}`;
                    await zip.extract(`${entry['name']}`, entryPath);

                    // 4- convert the .sqlite file to json so we can go through the db documents
                    const exporter = sqliteJson(entryPath);

                    const tables = await exporter.tables; //ps. there's no support for this directly it gives '[Function (anonymous)]'
                    console.log('tables:', tables);

                    exporter.tables(function (err, tables) {
                        for (let i = 0; i < tables.length; i++) {
                            console.log(tables[i]);
                            exporter.json(`select * FROM ${tables[i]}`, function (err, json) {
                                // console.log(json); do what i want here
                            });
                        }
                    });

                   **// could this be as  exporter.tables only supports callback not a promise that is awaited ??**
                    try {
                        await unlink(entryPath);
                        console.log('successfully deleted');
                    } catch (error) {
                        console.error('there was an error:', error.message);
                    }`

**Comment by fitnr** [comment]
I didn't realize that you were using this programatically, I assumed you were using the cli script.

Add this after you're done with the exporter:
```javascript
exporter.database.close()
```

**Comment by alialaraby** [comment]
sorry i did't explain it at the beginning and that did the trick thank you.
