### ISSUE TITLE
Command line usage for this pacakge doesn't work

### ISSUE THREAD

**Issue by nikhilnagaraju** [fitnr/sqlite-json#7]
i have installed `sqlite-json` package using `npm install sqlite-json --save` and tried the sqlite-json command as specified in readme. I get a error saying `sqlite-json: command not found`. I don't know how to use sqlite-json in js.

**Comment by fitnr** [comment]
If you install without the `-g` flag, you'll need to specify the path to the local executable:
```
node_modules/.bin/sqlite-json [options]
```

**Comment by nikhilnagaraju** [comment]
thank you so much for the support :-)
