### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">= 0.12,<5"

### ISSUE THREAD

**Issue by bennyn** [fitnr/sqlite-json#9]
I want to use the module with Node.js v8.9.4 and I think chances are high that it will work but unfortunately this version is blocked by the setting in your `package.json`:
- https://github.com/fitnr/sqlite-json/blob/v1.0.1/package.json#L26-L28

**Comment by fitnr** [comment]
I've pushed an update. I'll publish to npm later when I'm on an authenticated machine.
